# Generated by Django 4.2 on 2026-04-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan_coachprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='speciality',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
