# Generated by Django 4.2 on 2026-04-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_coachprofile_location_coachprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='benefits',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='sessions_count',
            field=models.IntegerField(default=0),
        ),
    ]
