# Generated by Django 4.2 on 2026-04-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_plan_benefits_plan_duration_plan_sessions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('elite', 'Elite')], default='basic', max_length=20),
        ),
    ]
