# Generated by Django 4.2 on 2026-04-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_plan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='coach_photos/'),
        ),
    ]
