# Generated by Django 4.2 on 2026-04-28 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_coachprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plans/images/')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.plan')),
            ],
        ),
    ]
