# Generated by Django 4.2 on 2026-05-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.CharField(choices=[('box', 'Box'), ('musculation', 'Musculation'), ('yoga', 'Yoga'), ('crossfit', 'Crossfit'), ('fitness', 'Fitness'), ('cardio', 'Cardio'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
