# Generated by Django 4.2 on 2026-05-05 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_trainingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('exercises', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('goal', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
