# Generated by Django 4.2 on 2026-05-05 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_clienttraininglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('goal', models.CharField(max_length=200)),
                ('total_sessions', models.IntegerField(default=0)),
                ('done_sessions', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('next_session_date', models.DateField(blank=True, null=True)),
                ('next_session_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
